name: Nick Padley - Digital Notes
description: Information about Nick's Hobbies
permalink: /:year/:month/:day/:title/
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
paginate: 5
paginate_path: /blog/page-:num
pygments: true
lessc: /usr/local/bin/lessc
url: http://www.nickpadley.com
exclude: ['Rakefile', Gemfile, Gemfile.lock, 'Personal Blog.esproj']
include: ['.htaccess']
assets:
  css_compressor: yui
  js_compressor:  yui