name: Nick Padley - Digital Notes
description: Information about Nick's Hobbies
permalink: /:year/:month/:day/:title/
paginate: 5
paginate_path: /blog/page-:num
pygments: true
url: http://www.nickpadley.com
exclude: [Gemfile, Gemfile.lock, 'Personal Blog.esproj', css/main.less]