backend:
  name: git-gateway
  branch: master # Branch to update

publish_mode: editorial_workflow

media_folder: "img/uploads" # Media files will be stored in the repo under images/uploads

collections:
  - name: "blog"
    label: "Blog Post"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Comments", name: "comments", widget: "hidden", default: "true"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}